name: playwright Hybrid

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers (and Linux deps)
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm run p1

      - name: Upload reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports
          if-no-files-found: ignore
