name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Verify page.config.js exists and resolves
        run: |
          set -euo pipefail
          echo "Listing probable locations:"
          ls -la pages || true
          node -e "console.log('Resolved:', require.resolve('./pages/page.config.js'))"
          node -e "const {pages}=require('./pages/page.config.js'); if(!pages||typeof pages!=='object') { throw new Error('pages export missing or not an object'); }"

      - name: Ensure reports dir
        run: mkdir -p reports

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run p1

      - name: Upload reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports
          if-no-files-found: ignore
